export type BlogPost = {
  id: string;
  title: string;
  url: string;
  date: string;
  excerpt: string;
  image?: string;
  category?: string;
  relatedStages?: string[];
  relatedTopics?: string[];
};

export const blogPosts = [
  {
    id: "prepare-for-pregnancy",
    title: "Як підготуватися до вагітності?",
    category: "expert-columns",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["basics"],
    excerpt: "Поради експертів щодо підготовки до вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/prepare-for-pregnancy",
    date: "2024-06-01",
  },
  {
    id: "ovulation-tips",
    title: "Овуляція: що потрібно знати?",
    category: "expert-columns",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["ovulation"],
    excerpt: "Важливі факти про овуляцію та фертильність...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/ovulation-tips",
    date: "2024-06-02",
  },
  {
    id: "healthy-nutrition",
    title: "Здорове харчування для майбутніх батьків",
    category: "product-reviews",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["nutrition"],
    excerpt: "Що їсти під час підготовки до вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/healthy-nutrition",
    date: "2024-06-03",
  },
  {
    id: "family-planning-tips",
    title: "Планування сім’ї: перші кроки",
    category: "parent-stories",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["family-planning"],
    excerpt: "Як почати планувати сім’ю...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/family-planning-tips",
    date: "2024-06-04",
  },
  {
    id: "reproductive-health-guide",
    title: "Репродуктивне здоров'я: основи та поради",
    category: "expert-columns",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["reproductive-health"],
    excerpt: "Як підтримувати репродуктивне здоров'я жінки та чоловіка...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/reproductive-health-guide",
    date: "2024-06-05",
  },
  {
    id: "prevention-checklist",
    title: "Профілактика та обстеження перед вагітністю",
    category: "expert-columns",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["prevention"],
    excerpt: "Які обстеження пройти перед плануванням вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/prevention-checklist",
    date: "2024-06-06",
  },
  {
    id: "psychology-prep",
    title: "Психологічна підготовка до батьківства",
    category: "parent-stories",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["psychology"],
    excerpt: "Як підготувати себе психологічно до нової ролі...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/psychology-prep",
    date: "2024-06-07",
  },
  {
    id: "pregnancy-trimester-guide",
    title: "Гід по триместрах вагітності",
    category: "expert-columns",
    relatedStages: ["pregnancy"],
    relatedTopics: ["by-trimesters"],
    excerpt: "Що відбувається з мамою та малюком у кожному триместрі?",
    image: "https://placehold.co/400x200/png",
    url: "/blog/pregnancy-trimester-guide",
    date: "2024-06-10",
  },
  {
    id: "pregnancy-weekly-calendar",
    title: "Вагітність по тижнях: календар змін",
    category: "expert-columns",
    relatedStages: ["pregnancy"],
    relatedTopics: ["by-weeks"],
    excerpt: "Детальний календар змін для майбутніх мам.",
    image: "https://placehold.co/400x200/png",
    url: "/blog/pregnancy-weekly-calendar",
    date: "2024-06-11",
  },
  {
    id: "mom-health-safety",
    title: "Здоров’я та безпека під час вагітності",
    category: "product-reviews",
    relatedStages: ["pregnancy"],
    relatedTopics: ["health-safety"],
    excerpt: "Як зберегти здоров'я та безпеку під час вагітності?",
    image: "https://placehold.co/400x200/png",
    url: "/blog/mom-health-safety",
    date: "2024-06-12",
  },
  {
    id: "birth-prep-checklist",
    title: "Чекліст підготовки до пологів",
    category: "parent-stories",
    relatedStages: ["pregnancy"],
    relatedTopics: ["birth-prep"],
    excerpt: "Що підготувати до пологів: досвід мами.",
    image: "https://placehold.co/400x200/png",
    url: "/blog/birth-prep-checklist",
    date: "2024-06-13",
  },
  {
    id: "mom-state-changes",
    title: "Стан мами: фізичні та емоційні зміни",
    category: "expert-columns",
    relatedStages: ["pregnancy"],
    relatedTopics: ["mom-state"],
    excerpt: "Які зміни відбуваються з мамою під час вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/mom-state-changes",
    date: "2024-06-14",
  },
  {
    id: "baby-development-milestones",
    title: "Розвиток дитини по тижнях",
    category: "expert-columns",
    relatedStages: ["pregnancy"],
    relatedTopics: ["baby-development"],
    excerpt: "Основні етапи розвитку малюка під час вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/baby-development-milestones",
    date: "2024-06-15",
  },
  {
    id: "nutrition-activity-tips",
    title: "Харчування та активність для майбутніх мам",
    category: "product-reviews",
    relatedStages: ["pregnancy"],
    relatedTopics: ["nutrition-activity"],
    excerpt: "Поради щодо харчування та фізичної активності під час вагітності...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/nutrition-activity-tips",
    date: "2024-06-16",
  },
  {
    id: "baby-prep-guide",
    title: "Підготовка до народження дитини: що потрібно знати?",
    category: "parent-stories",
    relatedStages: ["pregnancy"],
    relatedTopics: ["baby-prep"],
    excerpt: "Поради щодо підготовки до появи малюка у сім'ї...",
    image: "https://placehold.co/400x200/png",
    url: "/blog/baby-prep-guide",
    date: "2024-06-17",
  },
  {
    id: "newborn-month-1",
    title: "Перший місяць з новонародженим: що очікувати?",
    url: "/blog/newborn-month-1",
    date: "2024-06-01",
    excerpt: "Детальний гайд для батьків про перший місяць життя дитини: розвиток, догляд, харчування.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["newborn"],
    relatedTopics: ["month-by-month"],
    category: "expert-columns",
  },
  {
    id: "newborn-sleep-tips",
    title: "Сон немовляти: поради для спокійних ночей",
    url: "/blog/newborn-sleep-tips",
    date: "2024-06-02",
    excerpt: "Як організувати сон новонародженого та уникнути типових проблем.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["newborn"],
    relatedTopics: ["sleep"],
    category: "expert-columns",
  },
  {
    id: "newborn-bonding",
    title: "Емоційний зв’язок з дитиною: перші кроки",
    url: "/blog/newborn-bonding",
    date: "2024-06-03",
    excerpt: "Поради для батьків щодо формування емоційного зв’язку з новонародженим.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["newborn"],
    relatedTopics: ["emotional-bonding"],
    category: "expert-columns",
  },
  {
    id: "infant-month-1",
    title: "Перший місяць немовляти: розвиток та догляд",
    url: "/blog/infant-month-1",
    date: "2024-06-10",
    excerpt: "Що очікувати у першому місяці життя немовляти: розвиток, харчування, сон.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["infant"],
    relatedTopics: ["month-by-month"],
    category: "expert-columns",
  },
  {
    id: "infant-milestones",
    title: "Віхи розвитку немовляти: перший рік",
    url: "/blog/infant-milestones",
    date: "2024-06-11",
    excerpt: "Основні віхи розвитку немовляти у перший рік життя.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["infant"],
    relatedTopics: ["milestones"],
    category: "parent-stories",
  },
  {
    id: "infant-sleep-tips",
    title: "Сон немовляти: як організувати режим дня?",
    url: "/blog/infant-sleep-tips",
    date: "2024-06-12",
    excerpt: "Поради щодо сну та режиму дня для немовляти.",
    image: "https://placehold.co/400x200/png",
    relatedStages: ["infant"],
    relatedTopics: ["sleep-routine"],
    category: "expert-columns",
  },
]; 