export type Tool = {
  id: string;
  name: string;
  description: string;
  url: string;
  image: string;
  relatedStages: string[];
  relatedTopics: string[];
};

export const tools = [
  {
    id: "ovulation-calculator",
    name: "Калькулятор овуляції",
    description: "Інструмент для розрахунку днів овуляції.",
    url: "/tools/ovulation-calculator",
    image: "/images/tools/ovulation-calculator/Ovulation Calculator.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["ovulation"],
  },
  {
    id: "pregnancy-due-date-calculator",
    name: "Калькулятор дати пологів",
    description: "Розрахуйте приблизну дату пологів.",
    url: "/tools/pregnancy-due-date-calculator",
    image: "/images/tools/Pregnancy Due Date Calculator/Pregnancy Due Date Calculator.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["basics"],
  },
  {
    id: "conception-date-calculator",
    name: "Калькулятор дати зачаття",
    description: "Визначте ймовірну дату зачаття.",
    url: "/tools/conception-date-calculator",
    image: "/images/tools/Conception Date Calculator/Conception Date Calculator.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["ovulation"],
  },
  {
    id: "pregnancy-test",
    name: "Чи я вагітна?",
    description: "Дізнайтесь, чи ви вагітні, за допомогою простого тесту.",
    url: "/tools/pregnancy-test",
    image: "/images/tools/Am I Pregnant/Am I Pregnant.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["basics"],
  },
  {
    id: "family-budget-planner",
    name: "Калькулятор бюджету вагітності",
    description: "Плануйте витрати під час підготовки до вагітності.",
    url: "/tools/family-budget-planner",
    image: "/images/tools/Pregnancy Budget Calculator/Pregnancy Budget Calculator.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["family-planning"],
  },
  {
    id: "pregnancy-checklist",
    name: "Чекліст покупок до вагітності та в пологовий",
    description: "Список необхідних речей для майбутніх батьків.",
    url: "/tools/pregnancy-checklist",
    image: "/images/tools/Pregnancy and Delivery Room Shopping Checklist/Pregnancy and Delivery Room Shopping Checklist.webp",
    relatedStages: ["pregnancy-prep"],
    relatedTopics: ["basics", "family-planning"],
  },
  {
    id: "baby-name-finder",
    name: "Пошук імен для дітей",
    description: "Знайдіть ідеальне ім'я для вашої дитини.",
    url: "/tools/baby-name-finder",
    image: "/images/tools/Baby Name Finder/Baby Name Finder.webp",
    relatedStages: ["pregnancy"],
    relatedTopics: ["baby-prep"],
  },
  {
    id: "pregnancy-weight-gain-calculator",
    name: "Калькулятор збільшення ваги під час вагітності",
    description: "Відстежуйте здоровий набір ваги під час вагітності.",
    url: "/tools/pregnancy-weight-gain-calculator",
    image: "/images/tools/Pregnancy Weight Gain Calculator/Pregnancy Weight Gain Calculator.webp",
    relatedStages: ["pregnancy"],
    relatedTopics: ["mom-state"],
  },
  {
    id: "birth-plan-worksheet",
    name: "Робочий аркуш плану пологів",
    description: "Плануйте свої пологи з цим зручним аркушем.",
    url: "/tools/birth-plan-worksheet",
    image: "/images/tools/Birth Plan Worksheet/Birth Plan Worksheet.webp",
    relatedStages: ["pregnancy"],
    relatedTopics: ["birth-prep"],
  },
  {
    id: "chinese-gender-predictor",
    name: "Китайський прогностичний гендер",
    description: "Дізнайтесь стать дитини за китайським календарем.",
    url: "/tools/chinese-gender-predictor",
    image: "/images/tools/Chinese Gender Predictor/Chinese Gender Predictor.webp",
    relatedStages: ["pregnancy"],
    relatedTopics: ["baby-development"],
  },
  {
    id: "baby-tracker",
    name: "Дитячий трекер",
    description: "Відстежуйте розвиток та події немовляти.",
    image: "/images/tools/Baby Tracker/Baby Tracker.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/baby-tracker",
  },
  {
    id: "baby-expense-calculator",
    name: "Калькулятор витрат на дитину",
    description: "Плануйте бюджет для немовляти.",
    image: "/images/tools/Baby Expense Calculator/Baby Expense Calculator.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/baby-expense-calculator",
  },
  {
    id: "breastfeeding-solutions",
    name: "Вирішення проблем грудного вигодовування",
    description: "Поради та рішення для грудного вигодовування немовляти.",
    image: "/images/tools/Breastfeeding Solutions/Breastfeeding Solutions.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/breastfeeding-solutions",
  },
  {
    id: "growth-chart",
    name: "Таблиця росту дитини",
    description: "Відстежуйте ріст та вагу немовляти.",
    image: "/images/tools/Baby Growth Chart/Baby Growth Chart.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/growth-chart",
  },
  {
    id: "formula-feeding-solutions",
    name: "Вирішення проблем годування сумішшю",
    description: "Поради для годування сумішшю немовляти.",
    image: "/images/tools/Formula Feeding Solutions/Formula Feeding Solutions.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/formula-feeding-solutions",
  },
  {
    id: "registry",
    name: "Реєстр",
    description: "Список необхідних речей для немовляти.",
    image: "/images/tools/Registry/Registry.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/registry",
  },
  {
    id: "courses",
    name: "Курси",
    description: "Освітні курси для батьків немовлят.",
    image: "/images/tools/Courses/Courses.webp",
    relatedStages: ["newborn", "infant"],
    url: "/tools/courses",
  },
]; 