import { BookOpen, CalendarRange, HeartPulse, Stethoscope, Apple, HeartHandshake, Users, Layers, Baby, Bed, Milestone, Brain, Calendar } from "lucide-react";

export const topics = [
  {
    id: "basics",
    stageId: "pregnancy-prep",
    name: "Основи вагітності",
    icon: BookOpen,
    desc: "Базова інформація про підготовку до вагітності.",
    image: "/images/topics/prep/basics/basics.webp",
    tools: [], // tool IDs
    blogPosts: [], // blog post IDs
  },
  {
    id: "ovulation",
    stageId: "pregnancy-prep",
    name: "Овуляція та фертильність",
    icon: CalendarRange,
    desc: "Дізнайтесь про овуляцію та фертильність.",
    image: "/images/topics/prep/ovulation/ovulation.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "reproductive-health",
    stageId: "pregnancy-prep",
    name: "Репродуктивне здоров'я",
    icon: HeartPulse,
    desc: "Поради щодо репродуктивного здоров'я.",
    image: "/images/topics/prep/reproductive-health/reproductive-health.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "prevention",
    stageId: "pregnancy-prep",
    name: "Профілактика та обстеження",
    icon: Stethoscope,
    desc: "Важливість профілактики та обстежень.",
    image: "/images/topics/prep/prevention/prevention.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "nutrition",
    stageId: "pregnancy-prep",
    name: "Харчування та спосіб життя",
    icon: Apple,
    desc: "Здорове харчування та спосіб життя.",
    image: "/images/topics/prep/nutrition/nutrition.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "psychology",
    stageId: "pregnancy-prep",
    name: "Психологічна підготовка",
    icon: HeartHandshake,
    desc: "Психологічна підтримка та підготовка.",
    image: "/images/topics/prep/psychology/psychology.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "family-planning",
    stageId: "pregnancy-prep",
    name: "Планування сім’ї",
    icon: Users,
    desc: "Поради щодо планування сім’ї.",
    image: "/images/topics/prep/family-planning/family-planning.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "by-trimesters",
    stageId: "pregnancy",
    name: "За триместрами",
    icon: Layers,
    desc: "Вагітність по триместрах: основні етапи та зміни.",
    image: "/images/topics/pregnancy/trimester/by-trimester.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "by-weeks",
    stageId: "pregnancy",
    name: "По тижнях",
    icon: CalendarRange,
    desc: "Вагітність по тижнях: детальний календар.",
    image: "/images/topics/pregnancy/weeky/weekly.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "mom-state",
    stageId: "pregnancy",
    name: "Стан мами",
    icon: HeartPulse,
    desc: "Зміни та самопочуття майбутньої мами.",
    image: "/images/topics/pregnancy/mom-state/mom-state.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "baby-development",
    stageId: "pregnancy",
    name: "Розвиток дитини",
    icon: Baby,
    desc: "Як розвивається малюк під час вагітності.",
    image: "/images/topics/pregnancy/baby-development/baby-development.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "health-safety",
    stageId: "pregnancy",
    name: "Здоров’я та безпека",
    icon: Stethoscope,
    desc: "Поради щодо здоров'я та безпеки під час вагітності.",
    image: "/images/topics/pregnancy/health-safety/health-safety.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "nutrition-activity",
    stageId: "pregnancy",
    name: "Харчування та активність",
    icon: Apple,
    desc: "Здорове харчування та фізична активність для майбутніх мам.",
    image: "/images/topics/pregnancy/nutrition-activity/nutrition-activity.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "birth-prep",
    stageId: "pregnancy",
    name: "Підготовка до пологів",
    icon: BookOpen,
    desc: "Як підготуватися до пологів: поради та чеклісти.",
    image: "/images/topics/pregnancy/birth-prep/birth-prep.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "baby-prep",
    stageId: "pregnancy",
    name: "Підготовка до дитини",
    icon: Users,
    desc: "Що потрібно знати та підготувати до народження малюка.",
    image: "/images/topics/pregnancy/baby-prep/baby-prep.webp",
    tools: [],
    blogPosts: [],
  },
  {
    id: "month-by-month",
    stageId: "infant",
    name: "Дитина місяць за місяцем",
    icon: Milestone,
    desc: "Розвиток дитини по місяцях.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "milestones",
    stageId: "infant",
    name: "Розвиток і віхи",
    icon: Milestone,
    desc: "Ключові віхи розвитку немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "cognitive-sensory",
    stageId: "infant",
    name: "Когнітивний та сенсорний розвиток",
    icon: Brain,
    desc: "Розвиток мислення та відчуттів у немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "play-activities",
    stageId: "infant",
    name: "Ігри, активності та розвиток",
    icon: BookOpen,
    desc: "Ігри та активності для розвитку немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "nutrition",
    stageId: "infant",
    name: "Харчування",
    icon: Apple,
    desc: "Поради щодо харчування немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "sleep-routine",
    stageId: "infant",
    name: "Сон і режим дня",
    icon: Bed,
    desc: "Як організувати сон і режим дня немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "hygiene-safety",
    stageId: "infant",
    name: "Гігієна, догляд та безпека",
    icon: Stethoscope,
    desc: "Гігієна, догляд та безпека немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "health-pediatrician",
    stageId: "infant",
    name: "Здоров’я і візити до педіатра",
    icon: Stethoscope,
    desc: "Здоров’я немовляти та візити до лікаря.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "language-social",
    stageId: "infant",
    name: "Мова, соціальні навички та поведінка",
    icon: Users,
    desc: "Розвиток мови, соціальних навичок та поведінки.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "independence-skills",
    stageId: "infant",
    name: "Навички самостійності",
    icon: Milestone,
    desc: "Перші навички самостійності немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "parent-mental-health",
    stageId: "infant",
    name: "Батьки і ментальне здоров’я",
    icon: HeartPulse,
    desc: "Підтримка ментального здоров’я батьків.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "week-by-week",
    stageId: "newborn",
    name: "Дитина тиждень за тижнем",
    icon: Baby,
    desc: "Розвиток дитини по тижнях.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "baby-care",
    stageId: "newborn",
    name: "Догляд за новонародженим",
    icon: Stethoscope,
    desc: "Поради щодо догляду за новонародженим.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "hygiene-diapers",
    stageId: "newborn",
    name: "Гігієна та підгузки",
    icon: Stethoscope,
    desc: "Гігієна новонародженого та вибір підгузків.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "nutrition",
    stageId: "newborn",
    name: "Харчування",
    icon: Apple,
    desc: "Поради щодо харчування новонародженого.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "sleep",
    stageId: "newborn",
    name: "Сон немовляти",
    icon: Bed,
    desc: "Як організувати сон немовляти.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "milestones",
    stageId: "newborn",
    name: "Розвиток",
    icon: Milestone,
    desc: "Ключові віхи розвитку новонародженого.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "brain-senses",
    stageId: "newborn",
    name: "Мозок та відчуття",
    icon: Brain,
    desc: "Розвиток мозку та сенсорики.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "emotional-bonding",
    stageId: "newborn",
    name: "Емоційний зв’язок і поведінка",
    icon: HeartHandshake,
    desc: "Поведінка та емоційний зв’язок з дитиною.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "routine",
    stageId: "newborn",
    name: "Графіки та рутина",
    icon: Calendar,
    desc: "Як організувати рутину для новонародженого.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "health",
    stageId: "newborn",
    name: "Здоров’я новонародженого",
    icon: Stethoscope,
    desc: "Здоров’я та профілактика захворювань.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "postpartum-recovery",
    stageId: "newborn",
    name: "Відновлення",
    icon: HeartPulse,
    desc: "Відновлення після пологів.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  {
    id: "mom-mental-health",
    stageId: "newborn",
    name: "Емоційне здоров’я мами",
    icon: HeartPulse,
    desc: "Підтримка емоційного здоров’я мами.",
    image: "https://placehold.co/400x200/png",
    tools: [],
    blogPosts: [],
  },
  // Add more topics for other stages here
]; 